source "https://rubygems.org"

gem "capybara", "3.33"
gem "cucumber", "5.2"
gem "selenium-webdriver", "3.142.7"
gem "rspec", "3.9"
gem "httparty", "0.18.1"
gem "rufo", "0.12.0" #ajuda a formatar o código ruby. Tem que instalar uma extensão do rufo no VisualStudio
gem "allure-cucumber", "2.13.6.3"
